### ISSUE TITLE
No Price

### ISSUE THREAD

**Issue by dandud100** [vinc3PO/ebayKleinanzeigenAlert#13]
Hello, on Telegram it always shows "No Price" but there is one. Could you look into this. Thanks. ✌🏻

**Comment by nilsreichardt** [comment]
Same for me.

I'm using this eBay Kleinanzeigen link: https://www.ebay-kleinanzeigen.de/s-wohnung-mieten/muenchen/anzeige:angebote/c203l6411

<img width="469" alt="image" src="https://user-images.githubusercontent.com/24459435/192719413-1c8b8ac3-273a-44b2-b6d5-2df8a841812b.png">

**Comment by daniel22-git** [comment]
> Same for me.

I made a pull request, can you try if this fixes the problem? 😊
