### ISSUE TITLE
Beschreibung des Projekts

### ISSUE THREAD

**Issue by sveeen** [vinc3PO/ebayKleinanzeigenAlert#19]
Hallo! 

Grundsätzlich habe ich das kleine aber feine Tool verstanden. Ich habe es zum Laufen gebracht und Nachrichten bekomme ich auch. Allerdings würde ich es gerne etwas besser verstehen. Was läuft da genau im Hintergrund? 

Die abgespeicherten Ebay Kleinanzeigen Links werden aufgerufen. Was passiert dann genau? Wird dann immer der Inhalt "gegrabbed" oder nur die angezeigten Treffer? Zurzeit bekomme ich manchmal eine Telegram-Nachricht, aber teilweise sind die Anzeigen schon älter. Neue Anzeigen kommen gefühlt manchmal nicht "rein".

Fragen:
- Wie wird sichergestellt, dass Ebay Kleinanzeigen einen nicht "blockiert"? 
- Gibt es Erfahrungswerte wie oft das Script aufgerufen werden "darf"? Also jede Minute? Alle 5 Minuten?
- Wäre es denkbar, wenn das auf einem kleinen vServer läuft oder ist die Gefahr dann größer blockiert zu werden?

Vielen Dank

**Comment by vinc3PO** [comment]
Hi,
The basics of the program is that it fetch the article in the URL.
It will only look for the first page and will show only what you would see if you go to the website. 

I am not aware of blocking by Ebay Kleinanzeigen, but if you are pinging too many links to close to each other they might be IP blocking. 
To be real, how often new ads are put up? 
Every minute would be ridiculous and put you at risk to be blacklisted. 
Once every 10/20/30 minutes or every hour or once a day is really up to you.

Cheers,
