### ISSUE TITLE
Commands don't do what they are supposed to

### ISSUE THREAD

**Issue by his0car** [vinc3PO/ebayKleinanzeigenAlert#2]
The only things that are working is "ebAlert start", "ebAlert links" (gives no output) and "ebAlerts --help", things like 
"ebAlert links add "https://www.ebay-kleinanzeigen.de/s-pc-zubehoer-software/grafikkarten/anzeige:angebote/c225+pc_zubehoer_software.art_s:grafikkarten" "
or 
"ebAlert -a "https://www.ebay-kleinanzeigen.de/s-pc-zubehoer-software/grafikkarten/anzeige:angebote/c225+pc_zubehoer_software.art_s:grafikkarten" " 
do not work.

**Comment by vinc3PO** [comment]
Hi there,
Sorry for the long answering delay. I did not got any notification of an issue reported. 
I have update the readme as I have made a type.. 
The command `ebAlert` start will give you nothing if you have no link in the database. 
To show the help for the link submenu, you should type:
`ebAlert links --help`  that should give you the list of command you can access.
To add a new link to the database:
`ebAlert links -a "URL"` or `ebAlert links --add_url "url"`
and to see if that was actually added to the database
`ebAlert links -s`
Thank you for report issue
Vincent
