### ISSUE TITLE
NoneType ERROR

### ISSUE THREAD

**Issue by Keyser0512** [vinc3PO/ebayKleinanzeigenAlert#20]
I'm trying runnig the script on my Linux server, everything worked fine for 10mins and then I got following Error Message.

2022-11-20 14:10:27,421 - get_session in ebAlert.crud.base - ERROR - 'NoneType' object has no attribute 'replace'
ERROR:ebAlert.crud.base:'NoneType' object has no attribute 'replace'

Do you guys had the error as well and how do you fixed it?

I tried to solve by myself but its kinda strange. On my windows computer it totally works without any issues.

**Comment by tablesturn** [comment]
Yes, since updating to bullseye, I get a similar error when running the bot using Kubernetes:

```
File "/usr/local/lib/python3.9/site-packages/ebAlert/__main__.py", line 78, in add_post
    for post in posts:
TypeError: 'NoneType' object is not iterable
```

I was not able to fix the error.

**Comment by vinc3PO** [comment]
Hi, 
@tablesturn your error is not necessarly the same as @Keyser0512.
Could you both tell me which python is installed in your system. 
Edit: Checked the 3.9 python

**Comment by vinc3PO** [comment]
@tablesturn 
I look like that your are using an old version of the ebAlert.

**Comment by vinc3PO** [comment]
@Keyser0512 
Fixed the problem by handling exception when fetching the link fails for any reason.

**Comment by tablesturn** [comment]
> @tablesturn I look like that your are using an old version of the ebAlert.

Indeed, a closer look revealed that the docker container randombyte/ebay-kleinanzeigen-alert is a fork and not maintained any more. The easiest solution for me was to use the software natively.
