### ISSUE TITLE
Finding no more results

### ISSUE THREAD

**Issue by snp42** [vinc3PO/ebayKleinanzeigenAlert#3]
Is there an update to the script? It seems to stop working by finding no results.
AttributeError:` 'NoneType' object has no attribute 'text'

**Comment by vinc3PO** [comment]
Hi there, 
thanks for using it. 
They have indeed completely changed their formating of the website.
I have tried to make it a little more change proof. But I might break again when they will update there website. 
Just let me know

**Comment by vinc3PO** [comment]
Also be aware that I have added a pydantic dependency.
