### ISSUE TITLE
It's not working anymore?

### ISSUE THREAD

**Issue by veedge** [vinc3PO/ebayKleinanzeigenAlert#33]
Sadly it seems that this awesome script stopped working since yesterday? :(

**Comment by DanielZ3108** [comment]
Same problem.
Last message came on Thursday.

**Comment by Kamran12646** [comment]
Same problem here. Seems like Kleinanzeigen has changed Something.

**Comment by PS-RWU** [comment]
Same problem :(

**Comment by vinc3PO** [comment]
Look like there was some change in the layout of the website as well as some class name change used for the scrapping. I'll work that out a push a new update as soon as it is all sorted out

**Comment by vinc3PO** [comment]
Fix on v1.4
