### ISSUE TITLE
still working?

### ISSUE THREAD

**Issue by ziomekdjpl** [vinc3PO/ebayKleinanzeigenAlert#34]
Is it still working? It worked for me for about 6 months, last Friday it stopped. Scrips works ok, no errors, but I don't get any new messages in telegram. 

thsnks a lot

**Comment by Kamran12646** [comment]
The Script got updated just a few minutes ago. Should work now.

**Comment by Candelero** [comment]
How can I update the script on my Raspberry? By following the install steps I get the error:
~# git clone https://github.com/vinc3PO/ebayKleinanzeigenAlert
fatal: destination path 'ebayKleinanzeigenAlert' already exists and is not an empty directory.

**Comment by 2Frez** [comment]
> How can I update the script on my Raspberry?

You can update it by doing:
```
cd ebayKleinanzeigenAlert/
git pull
```
