### ISSUE TITLE
Syntax error thrown running for first time

### ISSUE THREAD

**Issue by eojjn** [vinc3PO/ebayKleinanzeigenAlert#38]
Hey so I'm just trying this out for the first time. Followed instructions and tried starting with
`python -m ebAlert`

unfortunately this doesn't work and I am given the following error:

`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "ebAlert/__init__.py", line 2, in <module>
    from ebAlert.core.config import settings
  File "ebAlert/core/config.py", line 9
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
                                                                                                           ^
SyntaxError: invalid syntax
`

**Comment by mfecher** [comment]
You are using python v2.x, but his project requires python v3.x (see [requirements here.](https://github.com/vinc3PO/ebayKleinanzeigenAlert))
