### ISSUE TITLE
AttributeError:  'EbayItem' object has no attribute 'price'

### ISSUE THREAD

**Issue by DoktorABCD** [vinc3PO/ebayKleinanzeigenAlert#4]
why doesnt it work i need help

**Comment by vinc3PO** [comment]
Hi there, 
A little bit more context could be helpfull. 
From the error, it look like that the program could not find the price for an item. 
I though maybe, ebaykeinanzeigen had chanced there website inner tags one more.
But it seems to work for me here, 

Could you provide more details please?
