### ISSUE TITLE
No response from Bot, after changeing URL_BASE

### ISSUE THREAD

**Issue by valimili** [vinc3PO/ebayKleinanzeigenAlert#40]
Hi @all, im interested in a https://www.tutti.ch BOT and thought i can just change the URL_BASE from config.rpy.
I could run everything without an error message but my bot doesn't respond. What am i doing wrong here?

**Comment by vinc3PO** [comment]
The thing is the scrapper is looking for tags in the HTML page that are custom made for the Ebay-kleinenzagen page. 
If you want a tutti.ch, you will need to change the code in the scrapper to find the right tags and not have any errors. 
But as such, it's not plug and play.
