### ISSUE TITLE
ebAlert : Kommando nicht gefunden

### ISSUE THREAD

**Issue by wiNJan** [vinc3PO/ebayKleinanzeigenAlert#42]
Moin, bei dem Befehl "ebAlert links --help" und auch "ebAlert -a "_Kleinanzeigenlink_"" wird mir stets der Fehler "Kommando nicht gefunden" ausgeworfen.

Das Starten mit dem Befehl "python -m ebAlert" funktioniert einwandfrei. 

Wo liegt der Fehler?

Danke Euch im Voraus!
Gruß

Für den Fall das es eventuell hilfreich ist: Der Befehl "pip install ." konnte anfangs nicht ausgeführt werden, hier erhielt ich die Fehlermeldung "externally-managed-environment". Durch die Befehle "cd /usr/lib/python3.11" und "sudo rm EXTERNALLY-MANAGED" konnte ich dann die Installation umsetzen.

**Comment by Kamran12646** [comment]
Dann müsstest du python -m ebAlert links -a Kleinanzeigenlink schreiben dann müsste es gehen

Oder einmal den Server neu starten dann geht es auch ohne das Python am Anfang, wenn man sich im korrekten Ordner befindet.

**Comment by wiNJan** [comment]
Merci! Das hat funktioniert, vielen Dank!

**Comment by wiNJan** [comment]
Das hinzufügen von dem Kleinanzeigenlink hat funktioniert. Jedoch bekomme ich, nachdem ich den crontab aktiviert habe, keinen Eintrag im "out.txt".

Zuerst eingegeben habe ich:
*/3 7-23 * * * /usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start › /home/pi/out.txt

dann

*/3 7-23 * * * /usr/bin/python /home/pi/ebayKleinanzeigenAlert/python -m ebAlert start › /home/pi/out.txt

bei Varianten habe ich keinen Eintrag im GNU nano 7.2

Da "ebAlert" zum Anfang schon nicht funktionierte, muss ich eine Anpassung in dem crontab vornehmen?

Danke im Voraus!
Gruß

**Comment by wiNJan** [comment]
> Das hinzufügen von dem Kleinanzeigenlink hat funktioniert. Jedoch bekomme ich, nachdem ich den crontab aktiviert habe, keinen Eintrag im "out.txt".
> 
> Zuerst eingegeben habe ich: */3 7-23 * * * /usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start › /home/pi/out.txt
> 
> dann
> 
> */3 7-23 * * * /usr/bin/python /home/pi/ebayKleinanzeigenAlert/python -m ebAlert start › /home/pi/out.txt
> 
> bei Varianten habe ich keinen Eintrag im GNU nano 7.2
> 
> Da "ebAlert" zum Anfang schon nicht funktionierte, muss ich eine Anpassung in dem crontab vornehmen?
> 
> Danke im Voraus! Gruß

Hi, leider bin ich hier noch nicht weitergekommen. Wer kann mir helfen?!

Danke im Voraus!
wiNJan

**Comment by wiNJan** [comment]
Hi, die Lösung ist doch einfacher als ich dachte.

Ich habe den Befehl von:

`*/3 7-23 * * * /usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start › /home/pi/out.txt`

in

`*/3 7-23 * * * /usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start`

geändert. Damit funktioniert es wunderbar.
Gruß wiNJan
