### ISSUE TITLE
Hilfe 

### ISSUE THREAD

**Issue by Dvid-Wagner** [vinc3PO/ebayKleinanzeigenAlert#5]
Ich verstehe einfach kein Wort.

Kann mir bitt jemand ein ausführliches Tutorial geben?

**Comment by vinc3PO** [comment]
Es tut mir leid.
Ich bin Franzose und mein Deutsch ist nicht gut genug, um ein Tutorial zu schreiben.

**Comment by daniel22-git** [comment]
Ich habe eins erstellt. Siehe: #11

**Comment by nilsreichardt** [comment]
Ich denke, wir können das Ticket jetzt schließen, oder?
