### ISSUE TITLE
get_session in ebAlert.db.crud - ERROR - (sqlite3.OperationalError)

### ISSUE THREAD

**Issue by mhumhu** [vinc3PO/ebayKleinanzeigenAlert#6]
while running this command "python3.8 -m ebAlert links -a https://www.ebay-kleinanzeigen.de/s-sega/k0" i'm getting this error:

2022-01-27 00:36:15,101 - get_session in ebAlert.db.crud - ERROR - (sqlite3.OperationalError) no such table: ebay_link
[SQL: INSERT INTO ebay_link (link) VALUES (?)]
[parameters: ('https://www.ebay-kleinanzeigen.de/s-sega/k0',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
ERROR:ebAlert.db.crud:(sqlite3.OperationalError) no such table: ebay_link
[SQL: INSERT INTO ebay_link (link) VALUES (?)]
[parameters: ('https://www.ebay-kleinanzeigen.de/s-sega/k0',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

python -m ebAlert links -s gives me this:
2022-01-27 00:40:29,221 - get_session in ebAlert.db.crud - ERROR - (sqlite3.OperationalError) no such table: ebay_link
[SQL: SELECT ebay_link.id AS ebay_link_id, ebay_link.link AS ebay_link_link
FROM ebay_link]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
ERROR:ebAlert.db.crud:(sqlite3.OperationalError) no such table: ebay_link
[SQL: SELECT ebay_link.id AS ebay_link_id, ebay_link.link AS ebay_link_link
FROM ebay_link]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

any idea how to fix it?

**Comment by vinc3PO** [comment]
Hi,
This was indeed a bug. 
The database was created before the models were added to the base.
I pushed a fix today.

**Comment by mhumhu** [comment]
Thanks for your reply :)
I solved it by manually creating the table/columns.
i will test the fix later on, thanks for the great work.

**Comment by vinc3PO** [comment]
Thank you.
Luckily there is not many table or column but still tedious.
