### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Knackwurst00** [vinc3PO/ebayKleinanzeigenAlert#8]
Hi, i think the issue is myself. I have problems in those two steps:

Install or run straight from the directory.
install with pip install .
run with python -m ebAlert

It doesnt allow me to start it with python. Im really a beginner. Do you have any good youtube videos as tutorial? Thanks

**Comment by vinc3PO** [comment]
Hi, 
My guess would be that your are trying to start the program from the wrong location. 
1. Clone the repository:  `git clone https://github.com/vinc3PO/ebayKleinanzeigenAlert.git` -> Given that you have git installed
2. run a terminal from the project folder. 
3.
- You can either install via pip; `pip install .` -> then you can run run it simply by typing `ebAlert`
- You can also run it without installing it: `python -m ebAlert`  -> but you must be in the root directory of the project.

Hope that is helping.
